train_data = {
  'good': True,
  'bad': False,
  'sad': False,
  'awful': False,
  'not good': False,
  'not bad': True,
  'not sad': True,
  'very well': True,
  'very sad': False,
  'i am well': True,
  'this is good': True,
  'i am bad': False,
  'this is bad': False,
  'i am sad': False,
  'this is sad': False,
  'i am not well': False,
  'this is not good': False,
  'i am not bad': True,
  'this is not sad': True,
  'i am very well': True,
  'this is very good': True,
  'i am very bad': False,
  'this is very sad': False,
  'i am good not bad': True,
  'this is good not bad': True,
  'i am bad not good': False,
  'i am good and well': True,
  'i am not good and not well': False,
  'i am not at all good': False,
  'i am not at all bad': True,
  'i am not at all well': False,
  'i am not at all sad': True,
  'this is not at all sad': True,
  'this is not at all well': False,
  'i am good right now': True,
  'i am bad right now': False,
  'this is bad right now': False,
  'i am sad right now': False,
  'i was good earlier': True,
  'i was well earlier': True,
  'i was bad earlier': False,
  'i was sad earlier': False,
  'this is very good right now': True,
  'this is very bad right now': False,
  'this is very sad right now': False,
  'this was very good earlier': True,
  'this was very bad earlier': False,
  'i was good and not bad earlier': True,
  'i was not good and not well earlier': False,
  'i am not at all bad or sad right now': True,
}

test_data = {
  'well': True,
  'not well': False,
  'very good': True,
  'very bad': False,
  'this is well': True,
  'i am good': True,
  'this is not well': False,
  'i am not good': False,
  'this is not bad': True,
  'i am not sad': True,
  'this is very well': True,
  'i am very good': True,
  'this is very bad': False,
  'i am very sad': False,
  'this is bad not good': False,
  'this is good and well': True,
  'this is not good and not well': False,
  'this is not at all good': False,
  'this is not at all bad': True,
  'this is good right now': True,
  'this is sad right now': False,
  'this was good earlier': True,
  'this was bad earlier': False,
  'this was not well and not good earlier': False,
  'i am not at all good or well right now': True,
}
